### ISSUE TITLE
C128 keyboard support?

### ISSUE THREAD

**Issue by banman11** [sideprojectslab/c64-blue#1]
Hello,

First up, I'd like to say this looks like a very interesting project.

I was wondering how hard would it be to add a few extra keystrokes to support the very few extra keys on a C128 keyboard?

**Comment by sideprojectslab** [comment]
Hello, as long as the hardware allows it it should be no problem. However I
need to look into the keyboard connector of the c128 to say for sure :)

**Comment by banman11** [comment]
The keyboard is basically the same thing as a C64 with a few extra lines. One is hardwired I believe. That is the 40/80 switch.
The actual interface is a sort of square 25 way D female connector.
The Commodore engineer's tried to make it as easy as possible to use off the shelf parts.


Here is an example of a third party adaptor which would very easily plug straight into your project.

https://www.tindie.com/products/retrofletch/c64-keyboard-to-c128-adaptor-commodore-128-c128d/

Just a side note with a small wiring rearrangement of the keyboard lines a c16/plus4 keyboard should work just fine as well with your project..

https://www.pcbway.com/project/shareproject/C64_Keyboard.html
