### ISSUE TITLE
Compatibility with Ultimate64 Elite?

### ISSUE THREAD

**Issue by pwartbichler** [sideprojectslab/c64-blue#4]
Hi,
Is this project compatible with the current version of the Ultimate64 Elite, and will it support upcoming versions?

Thanks!

**Comment by sideprojectslab** [comment]
Hello,

The Blue-64 can be used on the current version of the U64 by means of a
ribbon cable to relocate the board in an appropriate position. Gideon was
not planning to support reading joystick data from the keyboard header in
future version of the U64, which would make the blue-64 much less useful.
Fortunately I have been talking to him and he seemed to confirm that it
would be possible to enable this feature via software in future versionn of
the U64, so I'll keep you posted on the progress.

The best way to stay up to date is to join our discord server, where you
can also ask around other users that have been experimenting with the
Blue-64.

https://discord.gg/w6gvqyBG

Kind regards,

**Comment by pwartbichler** [comment]
Thanks for the update, this sounds very promising 👍
